name: JavaFX CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install JavaFX runtime
        run: |
          sudo apt-get update
          sudo apt-get install -y openjfx

      - name: Compile JavaFX files
        run: |
          mkdir -p out
          javac --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml -d out $(find src -name "*.java")

      - name: Run JavaFX app (headless)
        run: |
          xvfb-run java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml -cp out Main
